version: "3.8"

services:
  postgres:
    container_name: PostgreSQL
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    env_file:
      - ./docker-env/.env
    
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    
  redis:
    container_name: Redis
    image: redis
    ports:
      - "6379:6379"
  
  fastapi:
    container_name: FastAPI
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./docker-env/.env
    depends_on:
      - postgres
      - redis